### ISSUE TITLE
Are there any public OpenEthereum nodes with trace? (to speed up my development)

### ISSUE THREAD

**Issue by stefek99** [gnosis/safe-transaction-service#200]
I would like to modify the transaction service to include some of the transactions that were sent by the individual accounts. 

This is the thing I have in mind: https://github.com/gnosis/safe-react/issues/1732

 _(Safe App that is using `window ethereum` directly to call low importance transactions that do not require multisig)_

In order to include such transactions in the transaction list, I will need to modify the transactions service.

_(this is because you do a lot of heavy lifting with docker, postres, redis - I would like to use that existing infrastructure)_

### Tracing is required

> `ETHEREUM_TRACING_NODE_URL`: Http/s address of an OpenEthereum node with [tracing enabled](https://openethereum.github.io/JSONRPC-trace-module).

Here is a list: https://ethereumnodes.com/

I don't think they are OpenEthereum - most likely not. Even if they are, `tracing` is probably not enabled.

I will DYOR, I will check, I will try... **Maybe you know which one?**

**Maybe you can allow me to use yours?** 

_(while my full node is syncing, speaking to the IT department)_

Of course you don't want to share your internal infra widely to the internet, but if you could ping me on email@genesis.re that would be helpful 💪

**Comment by Uxio0** [comment]
Hi @stefek99 ,

I would love to see proposals and people builiding onto the transaction service, but i think your approach could be changed a bit. To accomplish what you want, e.g. `This is because some operations are considered "low risk" (such as whilitelisting) and a single signature is enough` the recommended way to do that would be to code a `safe module`, and that module could be configured as you want to require what you need. Take a look for example at our `AllowanceModule`, that allows users to get an allowance so they can get funds out of the Safe without requiring all the signatures as long as they don't exceed the limit: https://github.com/gnosis/safe-modules/blob/master/allowances/contracts/AlowanceModule.sol

Module transactions are indexed, so that way you would be able to get them from the transaction service.

> I don't think they are OpenEthereum - most likely not. Even if they are, tracing is probably not enabled.
They are not easy to get, you have to run your own. We are aware of that strong dependency, and currently we couldn't figure out another way to do that. Projects like `thegraph` that rely on ethereum traces have the same dependency.

> Maybe you know which one?
I'm not aware

> Maybe you can allow me to use yours?
No sorry, doing trace requests stress the node a lot, so our node is private

**Comment by stefek99** [comment]
Cool, thank you for suggestions.

Looking at: https://docs.gnosis.io/safe/docs/contracts_architecture/#3-module-management

> "Depending on the use case, modules could for instance allow the execution of transactions without requiring all confirmation."

![image](https://user-images.githubusercontent.com/249703/102505579-13f5dd80-407a-11eb-87f3-4dc20f47af6d.png)

If you don't know how to enable Safe Modules you are not allowed to use them?

**Comment by Uxio0** [comment]
Hi, I answered on discord. I'm closing this issue as this is not related to the transaction service

**Comment by ytrezq** [comment]
@stefek99 http://archivenode.net?
