### ISSUE TITLE
Use ipfs gateway to fetch metadata when only ipfs hash is provided

### ISSUE THREAD

**Issue by mikheevm** [gnosis/safe-transaction-service#285]
# What is needed?
Take the following metadata contact as an example: https://etherscan.io/address/0x4e5f6f949ebe5036889177047fdfec33211244c5#readContract

It returns the following URL for metadata JSON (`ipfsTokenUri(229)`):
```
ipfs://QmNnga7TrnxJUY2b4aEdVyTadgib1nG1gvSiAf6LHKopBr/223.json
```

Can we add support for such URLs to the transaction service? So it uses some IPFS gateway to fetch the metadata file. Currently, it's not fetched and returned metadata is empty

# Related issues
https://github.com/gnosis/safe-transaction-service/issues/283 but was closed because of a misunderstanding

**Comment by Uxio0** [comment]
#283 was closed because it was implemented by https://github.com/gnosis/safe-transaction-service/commit/ac97286170fce8ffa17ed3eefe2f2944b39fa01d 😉 

That metadata contract you are talking about is not compliant with the [ERC721 standard metadata extension](https://eips.ethereum.org/EIPS/eip-721), so the service is not detecting any url. The service is already resolving IPFS urls for tokens implementing the standard `tokenURI` method. Does it make sense? 🙂

**Comment by mikheevm** [comment]
@Uxio0 thanks, you're fast!

OpenSea recognizes the contract somehow though

**Comment by Uxio0** [comment]
> @Uxio0 thanks, you're fast!
> 
> OpenSea recognizes the contract somehow though

They use some ad-hoc behaviours and special logic for some contracts
