### ISSUE TITLE
Curve prices are not right

### ISSUE THREAD

**Issue by Uxio0** [gnosis/safe-transaction-service#303]
**Describe the bug**
Function https://curve.readthedocs.io/registry-registry.html#Registry.get_virtual_price_from_lp_token was used to get the price, but it doesn't seem to be right

**Expected behavior**
Price must match another platforms like Zerion.

**Additional context**
Zerion SDK can be used to get the underlying token assets

**Comment by tschubotz** [comment]
Some context on the `virtual_price` function on Curve:

- For example: The steCRV (ETH<>stETH) pool on curve uses the LP token at `0x06325440d014e39736583c165c2963ba99faf14e`
- That one has a “virtual_price_from_lp_token of `1016733357092025376,` devided by 1e18 that’s 1.016 etc
- There are ~894365 of those LP tokens in existence. I think you get 1 LP token for each ETH (or steETH you deposit)
- The pool currently holds ~448067 in ETH and ~461272 in stETH. 
- In curve pools, the assets are treated 1 to 1 as far as I know. 
- When summing up the ETH and stETH, the sum is: ~909339
- That’s higher than number of LP tokens (894365). The difference originates from the accumulated tx fees I think.
- In order to account for the difference, this “virtual share price” exists: 909339 / 894365 = 1.016  :slightly_smiling_face: 

So I think this is kind of a convenience function if you want to get your ETH/stETH balance just from the amount of LP tokens you hold.
For price calculation like we want to do it, we still have to consider the underlying. And instead of using this virtual share price, I think it’s easier to just check the ETH and stETH balance of the pool and then exchange this to USD or whatever.

**Comment by Uxio0** [comment]
I implemented it using Zerion adapter, but it's not returning the components for some addresses:

- Zerion adapter: https://etherscan.io/address/0x36c60c1CC2818ccb9eA5a1b87C0b309196D2D867#readContract
- `Curve.fi DAI/USDC...`: https://etherscan.io/address/0xc25a3a3b969415c80451098fa907ec722572917f . It's working
- `Curve.fi ETH/stETH (steCRV)`: https://etherscan.io/address/0x06325440d014e39736583c165c2963ba99faf14e . Not working

**Comment by tschubotz** [comment]
The Zerion Curve Token adapter at https://etherscan.io/address/0x36c60c1CC2818ccb9eA5a1b87C0b309196D2D867#readContract seems to be different from the code at https://github.com/zeriontech/defi-sdk/blob/interactive/contracts/adapters/curve/CurveTokenAdapter.sol - perhaps that the reason?

We have a Slack channel with Zerion - you could reach out to them there easily to clarify :)

**Comment by Uxio0** [comment]
Nice catch! I found out that the updated adapter for Curve is https://etherscan.io/address/0x99b0bEadc3984eab9842AF81f9fad0C2219108cc#readContract and is working now!
