### ISSUE TITLE
Change application base URL

### ISSUE THREAD

**Issue by air3ijai** [gnosis/safe-transaction-service#352]
### What is needed?

Change application base URL

### Background

We are deploying some Gnosis Safe Services together using a single entry entry point:
```
domain.tld/safe-transaction-service
domain.tld/safe-relay-service
domain.tld/safe-config-service
```
In front of each of the service we use Nginx as it is provided in the applications repositories and with additional rewrite to send request to the backend without first path in the URI:
```
location / {
  rewrite ^/.*?/(.*)$ /$1 break;
  ...
}
```
In such a way, request flow will look like:
```
Client --> Nginx: domain.tld/safe-transaction-service/api/v1/about/ --> App: /api/v1/about/
```
Such approach woks good but we observed the issue in the swagger. It anyway shows us `[ Base URL: domain.tld/api/v1 ]` instead of `[ Base URL: domain.tld/safe-transaction-service/api/v1 ]` and *Try it out* will fail.

Variable like `APP_BASE_PATH=/safe-transaction-service/` should permit us to not modify Nginx config and to use correctly swagger.

### Related issues

Same behaviour is observed for:
https://github.com/gnosis/safe-config-service
https://github.com/gnosis/safe-relay-service
https://github.com/gnosis/safe-client-gateway

**Comment by Uxio0** [comment]
Hi!

I would recommend if possible to use subdomains instead of messing with the path (e.g. safe-transaction.domain.tld). That's how we do it.

We use [drf-yasg](https://github.com/axnsan12/drf-yasg) to build the swagger schema. As they state in the docs, they [ignore the path when detecting the URL](https://drf-yasg.readthedocs.io/en/stable/openapi.html#custom-spec-base-url). I have been trying and there's no easy way to accomplish what you are trying to do. You can try this solution: https://github.com/axnsan12/drf-yasg/issues/146#issuecomment-478757552

**Comment by Uxio0** [comment]
Hi, this is now possible using #400

**Comment by air3ijai** [comment]
@Uxio0, thank you for the update!
We already followed your initial suggestion, but it is good to have an alternative.
